// @generated by protobuf-ts 2.5.0
// @generated from protobuf file "protobuf/protos/api/teams/TeamSeasonStats.proto" (package "ApiProtos.Teams.TeamSeasonStats", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats
 */
export interface TeamSeasonStats {
    /**
     * @generated from protobuf field: repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank bestPlayerRank = 1;
     */
    bestPlayerRank: TeamSeasonStats_BestPlayerRank[]; // 最佳球員排行
    /**
     * @generated from protobuf field: repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank bestPlayerRankHistory = 2;
     */
    bestPlayerRankHistory: TeamSeasonStats_BestPlayerRank[]; // 歷年最佳球員排行
    /**
     * @generated from protobuf field: repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.Player players = 3;
     */
    players: TeamSeasonStats_Player[]; // 球員列表
}
/**
 * @generated from protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.PlayerRank
 */
export interface TeamSeasonStats_PlayerRank {
    /**
     * @generated from protobuf field: int32 playerId = 1;
     */
    playerId: number; // 球員id
    /**
     * @generated from protobuf field: int32 teamId = 2;
     */
    teamId: number; // 球隊id
    /**
     * @generated from protobuf field: int32 position = 3;
     */
    position: number; // 排名
    /**
     * @generated from protobuf field: int32 total = 4;
     */
    total: number; // 排名
    /**
     * @generated from protobuf field: string seasonName = 5;
     */
    seasonName: string; // 賽季名稱
}
/**
 * @generated from protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank
 */
export interface TeamSeasonStats_BestPlayerRank {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string; // 榜單名稱
    /**
     * @generated from protobuf field: repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.PlayerRank rank = 2;
     */
    rank: TeamSeasonStats_PlayerRank[]; // 排行
}
/**
 * @generated from protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.Player
 */
export interface TeamSeasonStats_Player {
    /**
     * @generated from protobuf field: int32 id = 1;
     */
    id: number; // 球員id
    /**
     * @generated from protobuf field: string name = 2;
     */
    name: string; // 球員名稱
    /**
     * @generated from protobuf field: string logo = 3;
     */
    logo: string; // 球員logo
}
// @generated message type with reflection information, may provide speed optimized methods
class TeamSeasonStats$Type extends MessageType<TeamSeasonStats> {
    constructor() {
        super("ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats", [
            { no: 1, name: "bestPlayerRank", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TeamSeasonStats_BestPlayerRank },
            { no: 2, name: "bestPlayerRankHistory", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TeamSeasonStats_BestPlayerRank },
            { no: 3, name: "players", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TeamSeasonStats_Player }
        ]);
    }
    create(value?: PartialMessage<TeamSeasonStats>): TeamSeasonStats {
        const message = { bestPlayerRank: [], bestPlayerRankHistory: [], players: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TeamSeasonStats>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TeamSeasonStats): TeamSeasonStats {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank bestPlayerRank */ 1:
                    message.bestPlayerRank.push(TeamSeasonStats_BestPlayerRank.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank bestPlayerRankHistory */ 2:
                    message.bestPlayerRankHistory.push(TeamSeasonStats_BestPlayerRank.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.Player players */ 3:
                    message.players.push(TeamSeasonStats_Player.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TeamSeasonStats, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank bestPlayerRank = 1; */
        for (let i = 0; i < message.bestPlayerRank.length; i++)
            TeamSeasonStats_BestPlayerRank.internalBinaryWrite(message.bestPlayerRank[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank bestPlayerRankHistory = 2; */
        for (let i = 0; i < message.bestPlayerRankHistory.length; i++)
            TeamSeasonStats_BestPlayerRank.internalBinaryWrite(message.bestPlayerRankHistory[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.Player players = 3; */
        for (let i = 0; i < message.players.length; i++)
            TeamSeasonStats_Player.internalBinaryWrite(message.players[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats
 */
export const TeamSeasonStats = new TeamSeasonStats$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TeamSeasonStats_PlayerRank$Type extends MessageType<TeamSeasonStats_PlayerRank> {
    constructor() {
        super("ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.PlayerRank", [
            { no: 1, name: "playerId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "teamId", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "position", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "total", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "seasonName", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TeamSeasonStats_PlayerRank>): TeamSeasonStats_PlayerRank {
        const message = { playerId: 0, teamId: 0, position: 0, total: 0, seasonName: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TeamSeasonStats_PlayerRank>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TeamSeasonStats_PlayerRank): TeamSeasonStats_PlayerRank {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 playerId */ 1:
                    message.playerId = reader.int32();
                    break;
                case /* int32 teamId */ 2:
                    message.teamId = reader.int32();
                    break;
                case /* int32 position */ 3:
                    message.position = reader.int32();
                    break;
                case /* int32 total */ 4:
                    message.total = reader.int32();
                    break;
                case /* string seasonName */ 5:
                    message.seasonName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TeamSeasonStats_PlayerRank, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 playerId = 1; */
        if (message.playerId !== 0)
            writer.tag(1, WireType.Varint).int32(message.playerId);
        /* int32 teamId = 2; */
        if (message.teamId !== 0)
            writer.tag(2, WireType.Varint).int32(message.teamId);
        /* int32 position = 3; */
        if (message.position !== 0)
            writer.tag(3, WireType.Varint).int32(message.position);
        /* int32 total = 4; */
        if (message.total !== 0)
            writer.tag(4, WireType.Varint).int32(message.total);
        /* string seasonName = 5; */
        if (message.seasonName !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.seasonName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.PlayerRank
 */
export const TeamSeasonStats_PlayerRank = new TeamSeasonStats_PlayerRank$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TeamSeasonStats_BestPlayerRank$Type extends MessageType<TeamSeasonStats_BestPlayerRank> {
    constructor() {
        super("ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "rank", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TeamSeasonStats_PlayerRank }
        ]);
    }
    create(value?: PartialMessage<TeamSeasonStats_BestPlayerRank>): TeamSeasonStats_BestPlayerRank {
        const message = { name: "", rank: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TeamSeasonStats_BestPlayerRank>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TeamSeasonStats_BestPlayerRank): TeamSeasonStats_BestPlayerRank {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.PlayerRank rank */ 2:
                    message.rank.push(TeamSeasonStats_PlayerRank.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TeamSeasonStats_BestPlayerRank, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* repeated ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.PlayerRank rank = 2; */
        for (let i = 0; i < message.rank.length; i++)
            TeamSeasonStats_PlayerRank.internalBinaryWrite(message.rank[i], writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.BestPlayerRank
 */
export const TeamSeasonStats_BestPlayerRank = new TeamSeasonStats_BestPlayerRank$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TeamSeasonStats_Player$Type extends MessageType<TeamSeasonStats_Player> {
    constructor() {
        super("ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.Player", [
            { no: 1, name: "id", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "logo", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<TeamSeasonStats_Player>): TeamSeasonStats_Player {
        const message = { id: 0, name: "", logo: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<TeamSeasonStats_Player>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TeamSeasonStats_Player): TeamSeasonStats_Player {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* int32 id */ 1:
                    message.id = reader.int32();
                    break;
                case /* string name */ 2:
                    message.name = reader.string();
                    break;
                case /* string logo */ 3:
                    message.logo = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TeamSeasonStats_Player, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* int32 id = 1; */
        if (message.id !== 0)
            writer.tag(1, WireType.Varint).int32(message.id);
        /* string name = 2; */
        if (message.name !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.name);
        /* string logo = 3; */
        if (message.logo !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.logo);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Teams.TeamSeasonStats.TeamSeasonStats.Player
 */
export const TeamSeasonStats_Player = new TeamSeasonStats_Player$Type();
