// @generated by protobuf-ts 2.5.0
// @generated from protobuf file "protobuf/protos/socket/SystemInfo.proto" (package "socketProtos.SystemInfo", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Command } from "./Socket";
/**
 * @generated from protobuf message socketProtos.SystemInfo.SystemMaintain
 */
export interface SystemMaintain {
    /**
     * @generated from protobuf field: socketProtos.command.Command command = 1;
     */
    command: Command;
    /**
     * @generated from protobuf field: string eventTip = 2;
     */
    eventTip: string; // 維護結束時間
}
// @generated message type with reflection information, may provide speed optimized methods
class SystemMaintain$Type extends MessageType<SystemMaintain> {
    constructor() {
        super("socketProtos.SystemInfo.SystemMaintain", [
            { no: 1, name: "command", kind: "enum", T: () => ["socketProtos.command.Command", Command] },
            { no: 2, name: "eventTip", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SystemMaintain>): SystemMaintain {
        const message = { command: 0, eventTip: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<SystemMaintain>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SystemMaintain): SystemMaintain {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* socketProtos.command.Command command */ 1:
                    message.command = reader.int32();
                    break;
                case /* string eventTip */ 2:
                    message.eventTip = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SystemMaintain, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* socketProtos.command.Command command = 1; */
        if (message.command !== 0)
            writer.tag(1, WireType.Varint).int32(message.command);
        /* string eventTip = 2; */
        if (message.eventTip !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.eventTip);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message socketProtos.SystemInfo.SystemMaintain
 */
export const SystemMaintain = new SystemMaintain$Type();
