// @generated by protobuf-ts 2.5.0
// @generated from protobuf file "protobuf/protos/api/popular/PopularMatches.proto" (package "ApiProtos.Popular.PopularMatches", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PopularMatches_PopularMatch } from "../../socket/MatchInfo";
/**
 * @generated from protobuf message ApiProtos.Popular.PopularMatches.PopularMatches
 */
export interface PopularMatches {
    /**
     * @generated from protobuf field: repeated socketProtos.MatchInfo.PopularMatches.PopularMatch payload = 1;
     */
    payload: PopularMatches_PopularMatch[]; // 賽事列表
}
// @generated message type with reflection information, may provide speed optimized methods
class PopularMatches$Type extends MessageType<PopularMatches> {
    constructor() {
        super("ApiProtos.Popular.PopularMatches.PopularMatches", [
            { no: 1, name: "payload", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PopularMatches_PopularMatch }
        ]);
    }
    create(value?: PartialMessage<PopularMatches>): PopularMatches {
        const message = { payload: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PopularMatches>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PopularMatches): PopularMatches {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated socketProtos.MatchInfo.PopularMatches.PopularMatch payload */ 1:
                    message.payload.push(PopularMatches_PopularMatch.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PopularMatches, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated socketProtos.MatchInfo.PopularMatches.PopularMatch payload = 1; */
        for (let i = 0; i < message.payload.length; i++)
            PopularMatches_PopularMatch.internalBinaryWrite(message.payload[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Popular.PopularMatches.PopularMatches
 */
export const PopularMatches = new PopularMatches$Type();
