// @generated by protobuf-ts 2.5.0
// @generated from protobuf file "protobuf/protos/api/players/PlayersHonor.proto" (package "ApiProtos.Players.PlayersHonor", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message ApiProtos.Players.PlayersHonor.PlayersHonor
 */
export interface PlayersHonor {
    /**
     * @generated from protobuf field: repeated ApiProtos.Players.PlayersHonor.PlayersHonor.HonorItem payload = 1;
     */
    payload: PlayersHonor_HonorItem[]; // 榮耀列表
}
/**
 * @generated from protobuf message ApiProtos.Players.PlayersHonor.PlayersHonor.seasonInfo
 */
export interface PlayersHonor_seasonInfo {
    /**
     * @generated from protobuf field: string seasonName = 1;
     */
    seasonName: string; // 賽季名稱
    /**
     * @generated from protobuf field: string teamLogo = 2;
     */
    teamLogo: string; // 獲獎時球隊icon
}
/**
 * @generated from protobuf message ApiProtos.Players.PlayersHonor.PlayersHonor.HonorItem
 */
export interface PlayersHonor_HonorItem {
    /**
     * @generated from protobuf field: string name = 1;
     */
    name: string; // 榮譽名稱
    /**
     * @generated from protobuf field: string logo = 2;
     */
    logo: string; // 圖片
    /**
     * @generated from protobuf field: uint32 count = 3;
     */
    count: number; // 獲得次數
    /**
     * @generated from protobuf field: repeated ApiProtos.Players.PlayersHonor.PlayersHonor.seasonInfo seasons = 4;
     */
    seasons: PlayersHonor_seasonInfo[]; // 榮譽賽季
}
// @generated message type with reflection information, may provide speed optimized methods
class PlayersHonor$Type extends MessageType<PlayersHonor> {
    constructor() {
        super("ApiProtos.Players.PlayersHonor.PlayersHonor", [
            { no: 1, name: "payload", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PlayersHonor_HonorItem }
        ]);
    }
    create(value?: PartialMessage<PlayersHonor>): PlayersHonor {
        const message = { payload: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PlayersHonor>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayersHonor): PlayersHonor {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated ApiProtos.Players.PlayersHonor.PlayersHonor.HonorItem payload */ 1:
                    message.payload.push(PlayersHonor_HonorItem.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlayersHonor, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated ApiProtos.Players.PlayersHonor.PlayersHonor.HonorItem payload = 1; */
        for (let i = 0; i < message.payload.length; i++)
            PlayersHonor_HonorItem.internalBinaryWrite(message.payload[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Players.PlayersHonor.PlayersHonor
 */
export const PlayersHonor = new PlayersHonor$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlayersHonor_seasonInfo$Type extends MessageType<PlayersHonor_seasonInfo> {
    constructor() {
        super("ApiProtos.Players.PlayersHonor.PlayersHonor.seasonInfo", [
            { no: 1, name: "seasonName", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "teamLogo", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<PlayersHonor_seasonInfo>): PlayersHonor_seasonInfo {
        const message = { seasonName: "", teamLogo: "" };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PlayersHonor_seasonInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayersHonor_seasonInfo): PlayersHonor_seasonInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string seasonName */ 1:
                    message.seasonName = reader.string();
                    break;
                case /* string teamLogo */ 2:
                    message.teamLogo = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlayersHonor_seasonInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string seasonName = 1; */
        if (message.seasonName !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.seasonName);
        /* string teamLogo = 2; */
        if (message.teamLogo !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.teamLogo);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Players.PlayersHonor.PlayersHonor.seasonInfo
 */
export const PlayersHonor_seasonInfo = new PlayersHonor_seasonInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlayersHonor_HonorItem$Type extends MessageType<PlayersHonor_HonorItem> {
    constructor() {
        super("ApiProtos.Players.PlayersHonor.PlayersHonor.HonorItem", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "logo", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "count", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "seasons", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => PlayersHonor_seasonInfo }
        ]);
    }
    create(value?: PartialMessage<PlayersHonor_HonorItem>): PlayersHonor_HonorItem {
        const message = { name: "", logo: "", count: 0, seasons: [] };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<PlayersHonor_HonorItem>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: PlayersHonor_HonorItem): PlayersHonor_HonorItem {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string logo */ 2:
                    message.logo = reader.string();
                    break;
                case /* uint32 count */ 3:
                    message.count = reader.uint32();
                    break;
                case /* repeated ApiProtos.Players.PlayersHonor.PlayersHonor.seasonInfo seasons */ 4:
                    message.seasons.push(PlayersHonor_seasonInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: PlayersHonor_HonorItem, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string logo = 2; */
        if (message.logo !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.logo);
        /* uint32 count = 3; */
        if (message.count !== 0)
            writer.tag(3, WireType.Varint).uint32(message.count);
        /* repeated ApiProtos.Players.PlayersHonor.PlayersHonor.seasonInfo seasons = 4; */
        for (let i = 0; i < message.seasons.length; i++)
            PlayersHonor_seasonInfo.internalBinaryWrite(message.seasons[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message ApiProtos.Players.PlayersHonor.PlayersHonor.HonorItem
 */
export const PlayersHonor_HonorItem = new PlayersHonor_HonorItem$Type();
